[DEN-307] Update Integration Tests to Support Import
EdgeCast/terraform-provider-edgecast pull request #93
Opened 2022-05-23 20:55 UTC by defstream

# What's new?
- Added `populate` cmd to generate test data used in integration tests.
- Updated Taskfile to load test ids via environment
- Updated documentation with how to generate test data and how to run the integration tests. 

# Tested?
- Tests are confirmed by running `task` at the root of the project.

2022-06-02 21:00 UTC, stevenpaz requested changes
Looks great, just needs to include the recent bot rule sets stuff

2022-06-03 22:09 UTC, stevenpaz commented on edgecast/resources/rulesengine/v4policy.go
> +	return reflect.DeepEqual(oldPolicy, newPolicy) != false
Ah I should have caught this the first time I reviewed this code. Perhaps just leave it as `return reflect.DeepEqual(oldPolicy, newPolicy)` however. The `!=` is a little bit confusing.

2022-06-06 20:49 UTC, wdawg33 approved these changes
Nice work!

2022-06-07 16:59 UTC, ssaluja4 approved these changes

2022-06-07 18:20 UTC, merged